- Makefile
- cmd/config.go
- cmd/download.go
- cmd/install.go
- cmd/version.go
FIX #10 
I don't know if it is the right implementation, but have tested with a simple furyfile.yml file and it works.
@phisco, let me know if it works for you.
Once compiled, execute `furyctl install --htps`
Thanks!
> git via https

- .drone.yml
- .goreleaser.yml
- README.md
As furyagent, i've created the same logic also here.
> introducing goreleaser also in furyctl

- Furyfile.yml
- cmd/config.go
Hi everyone 👋 !
as asked by @nutellinoit , i implemented in furyctl the feature to customize the yaml in order to support also public terraform modules from terraform registry. It works, please review the code and ask for everything is you see some lacks or mistakes!
> added capability to handle fetch from public terraform registry

- docs/design/001-Cluster-Self-Provisioning.md
Ciao team!
This document is the one already reviewed in these two PRs:
- https://github.com/sighupio/sighup-cli-poc/pull/2
- https://github.com/sighupio/sighup-cli-poc/pull/1
I left only the tech section. Let me know if everything is fine!
> Move tech section of the furyctl cvi to this repo

- cmd/download.go
- cmd/init.go
This PR should solve the issue raised by @nikever  in issue #26
> fix issue #26

- docs/design/002-Cluster-Self-Provisioning - GKE.md
I am adding this cvi doc to continue with the furyctl self-provisioning feature to add GKE / Google Cloud provisioners.
> Add 002-Cluster-Self-Provisioning - GKE.md

- data/provisioners/cluster/eks/main.tf
- data/provisioners/cluster/eks/output.tf
- go.mod
- go.sum
More information here: https://github.com/sighupio/fury-eks-installer/pull/12
> Update eks cluster provisioner with the a fix related to the oidc url

- README.md
As per title, added infos on README on asdf plugin installation
> Add asdf install infos, asdf-vm/asdf-plugins#555

- .goreleaser.yml
As per title, goreleaser is not working correctly
> [HOTFIX] - Update .goreleaser using `ids[]`

- internal/cluster/configuration/gke.go
- internal/cluster/provisioners/gke/provisioner.go
- internal/configuration/config.go
- internal/configuration/templates.go
hi everyone 👋 ,
working side by side with the repo of furyctl I noticed these typos.
> Typo in struct for GKE provider

- cmd/bootstrap.go
- cmd/cluster.go
- internal/provisioners/provisioners.go
This PR aims to add the list of supported provisioners to cluster/bootstrap template cmd
> fix: added valid options for provisioners

- cmd/bootstrap.go
- cmd/cluster.go
Currently, the provisioner flag is case sentive. This PR aims to solve this problem, lowerizing the provisioner flag value.
> fix: provisioner flag is case sensitive

- internal/apis/kfd/v1alpha2/eks/create/infrastructure.go
Warn the user that he will be asked for their sudo password
> Improve VPN connection messages

- go.mod
- go.sum
- test/data/e2e/create/cluster/data/furyctl-defaults.yaml
- test/data/e2e/create/cluster/data/furyctl.yaml
- test/data/e2e/create/cluster/data/schemas/ekscluster-kfd-v1alpha2.json
- test/data/e2e/download/dependencies/v1.24.1/distro/furyctl-defaults.yaml
- test/data/e2e/download/dependencies/v1.24.1/distro/schemas/ekscluster-kfd-v1alpha2.json
- test/data/e2e/dump/template/complex-dry-run/furyctl-defaults.yaml
- test/data/e2e/dump/template/complex-dry-run/furyctl.yaml
- test/data/e2e/dump/template/complex/furyctl-defaults.yaml
- test/data/e2e/validate/config/correct/furyctl-defaults.yaml
- test/data/e2e/validate/config/correct/furyctl.yaml
- test/data/e2e/validate/config/correct/schemas/ekscluster-kfd-v1alpha2.json
- test/data/e2e/validate/config/wrong/furyctl-defaults.yaml
- test/data/e2e/validate/config/wrong/schemas/ekscluster-kfd-v1alpha2.json
- test/data/expensive/common/data/furyctl-defaults.yaml
- test/data/expensive/common/data/schemas/ekscluster-kfd-v1alpha2.json
- test/data/expensive/common/data/templates/distribution/manifests/dr/resources/velero-backupstoragelocation.yml.tpl
- test/data/expensive/common/data/templates/distribution/terraform/velero.tf.tpl
- test/data/integration/v1.24.1/distro/furyctl-defaults.yaml
- test/data/integration/v1.24.1/distro/schemas/ekscluster-kfd-v1alpha2.json
Changelist:
- renamed all bucket occurrences to bucketName, updated go.mod/go.sum to use new schema from https://github.com/sighupio/fury-distribution/pull/37/commits/ad0c881984b36bfc8511b80e027d586c452de612
> feat: renamed bucket to bucketName

- cmd/create.go
- cmd/create/cluster.go
- cmd/create/config.go
- cmd/delete.go
- cmd/delete/cluster.go
- cmd/download.go
- cmd/download/dependencies.go
- cmd/root.go
- cmd/validate.go
- cmd/validate/config.go
- cmd/validate/dependencies.go
- internal/distribution/download.go
- internal/distribution/download_test.go
Changelist:
- removed function `checkFuryctlBinVersion` from the dependencies validation step and refactored accordingly
> feat: removed furyctl binary version check

- internal/apis/kfd/v1alpha2/eks/create/distribution.go
- internal/tool/kubectl/runner.go
Changelist:
- distribution(dry-run): output terraform plan and kustomize build
example:
> feat: added dry-run logic in phase distribution to create cluster cmd

- go.mod
- go.sum
- internal/apis/kfd/v1alpha2/eks/create/infrastructure.go
- internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
- internal/template/mapper/mapper.go
- internal/template/mapper/mapper_test.go
- internal/x/bytes/buffer.go
- internal/x/bytes/buffer_test.go
Changelist:
- added support to file:// and env:// in phase infrastructure and kubernetes
- fixed some wrong tf_var generated data in phase kubernetes
closes #164
> Feat: support file:// and env:// for every phase in furyctl.yaml

- cmd/completion.go
- cmd/root.go
- main.go
> Fix: auto-complete not working due to logrus

- internal/dependencies/download.go
Changelist:
- added folder removal before downloading a module/installer
- added .git subfolder removal after downloading a module/installer
closes #167
> Feat: clean up vendor folder before dl and remove .git subfolder after dl

- internal/apis/kfd/v1alpha2/eks/create/distribution.go
- internal/apis/kfd/v1alpha2/eks/creator.go
- internal/apis/kfd/v1alpha2/eks/delete/distribution.go
- internal/dependencies/tools/kubectl_test.go
- internal/tool/kubectl/runner.go
- internal/tool/kubectl/runner_test.go
- internal/tool/runner.go
Changelist:
- added connectivity check into cluster create phase distribution by running kubectl version without flag --client 
- added connectivity check into cluster delete phase distribution by running kubectl version without flag --client 
closes #168
> Feat: check cluster connectivity in distribution phase

- cmd/validate/dependencies.go
- internal/dependencies/tools/kubectl.go
- internal/dependencies/tools/test_data/kubectl/1.21.1/kubectl
- internal/dependencies/tools/test_data/kubectl/1.22.0/kubectl
- internal/dependencies/tools/tool_test.go
- internal/tool/kubectl/runner.go
- test/data/e2e/validate/dependencies/correct/kubectl/1.24.9/kubectl
- test/data/e2e/validate/dependencies/wrong/kubectl/1.24.9/kubectl
> Feat: switched to output json in command kubectl version

- internal/tool/furyagent/runner.go
> Fix: returns instead of replacing the ovpn file with blank

- go.mod
- go.sum
- internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
- test/data/e2e/create/cluster/data/furyctl.yaml
- test/data/e2e/create/cluster/data/schemas/ekscluster-kfd-v1alpha2.json
- test/data/e2e/create/config/default/data/expected-furyctl.yaml
- test/data/e2e/create/config/distro/templates/config/ekscluster-kfd-v1alpha2.yaml.tpl
- test/data/e2e/download/dependencies/v1.24.1/furyctl.yaml
- test/data/e2e/dump/template/complex-dry-run/furyctl.yaml
- test/data/e2e/dump/template/complex/furyctl.yaml
- test/data/e2e/validate/config/correct/furyctl.yaml
- test/data/e2e/validate/config/correct/schemas/ekscluster-kfd-v1alpha2.json
- test/data/e2e/validate/config/nodistro/furyctl.yaml
- test/data/e2e/validate/config/wrong/furyctl.yaml
- test/data/e2e/validate/config/wrong/schemas/ekscluster-kfd-v1alpha2.json
- test/data/e2e/validate/dependencies/correct/furyctl.yaml
- test/data/e2e/validate/dependencies/missing/furyctl.yaml
- test/data/e2e/validate/dependencies/wrong/furyctl.yaml
- test/data/expensive/create-complete/data/furyctl.yaml
- test/data/expensive/create-skip-infra/data/furyctl.yaml
- test/data/expensive/create-skip-kube/data/furyctl.yaml
- test/data/integration/v1.24.1/furyctl.yaml
> Feat: added support to LogRetentionDays and NodePoolsLaunchKind

- cmd/create/cluster.go
- cmd/delete/cluster.go
- internal/apis/kfd/v1alpha2/eks/create/distribution.go
- internal/apis/kfd/v1alpha2/eks/create/infrastructure.go
- internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
- internal/apis/kfd/v1alpha2/eks/creator.go
- internal/apis/kfd/v1alpha2/eks/delete/distribution.go
- internal/apis/kfd/v1alpha2/eks/delete/infrastructure.go
- internal/apis/kfd/v1alpha2/eks/delete/kubernetes.go
- internal/apis/kfd/v1alpha2/eks/deleter.go
Changelist:
- improved Info messages in all phases delete/create command
- added export kubeconfig message
closes #151
> Feat: added export kubeconfig message

- .goreleaser.yml
- README.md
- cmd/create.go
- cmd/create/cluster.go
- cmd/create/config.go
- cmd/delete.go
- cmd/delete/cluster.go
- cmd/download.go
- cmd/download/dependencies.go
- cmd/dump.go
- cmd/root.go
- cmd/validate.go
- cmd/validate/config.go
- cmd/validate/dependencies.go
- internal/apis/kfd/v1alpha2/eks/creator.go
- internal/apis/kfd/v1alpha2/eks/deleter.go
- internal/cluster/deleter.go
- test/e2e/furyctl_test.go
- Update furyctl's Readme with NG way of doing things with basic and advance usage instructions
- Improve help messages and some errors
- standardize spelling for furyctl
closes #159
> Feat: update README for furyctl-ng

- cmd/delete/cluster.go
- internal/apis/kfd/v1alpha2/eks/create/infrastructure.go
- internal/apis/kfd/v1alpha2/eks/creator.go
- internal/apis/kfd/v1alpha2/eks/delete/infrastructure.go
- internal/apis/kfd/v1alpha2/eks/deleter.go
- internal/apis/kfd/v1alpha2/eks/init.go
- internal/cluster/deleter.go
- internal/tool/openvpn/runner.go
- internal/x/exec/root.go
- internal/x/os/root.go
- test/expensive/furyctl_test.go
Changelist:
- added isRoot function to check if the current user is root
- modified all log messages/commands that were dependent from sudo
- added info at the end of cluster creation/infra creation about killing the VPN connection after finishing doing operations on the cluster
closes #140
> Feat: only use sudo if necessary

- cmd/create/cluster.go
> Feat: in dry run mode remove prints commands outputs

- cmd/create/config.go
- internal/config/validate.go
> Chore: moved path validation before distro download

- cmd/create/cluster.go
- cmd/delete/cluster.go
> Fix: now --dry-run does not imply --debug for external tools

- cmd/create/cluster.go
> Feat: check if kubeconfig file exists

- internal/apis/kfd/v1alpha2/eks/creator.go
> Fix: check that the infra section exists before infra phase

- configs/provisioners/cluster/eks/main.tf.tpl
> Fix: added to template logRetentionDays and launchKind

- internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
> fix: added ami to tfvars in nodepools

- .drone.yml
- cmd/create/config.go
- cmd/root.go
- cmd/validate/dependencies.go
- go.mod
- go.sum
- internal/dependencies/download.go
- internal/dependencies/tools/tool.go
- internal/dependencies/tools/validator.go
- internal/dependencies/tools/validator_test.go
- internal/dependencies/toolsconf/validator.go
- internal/dependencies/validate.go
- internal/semver/compare.go
- internal/semver/compare_test.go
- internal/tool/awscli/runner.go
- test/data/e2e/create/cluster/bin_mock/aws
- test/data/e2e/create/cluster/data/kfd.yaml
- test/data/e2e/create/config/distro/kfd.yaml
- test/data/e2e/download/dependencies/v1.24.1/distro/kfd.yaml
- test/data/e2e/validate/config/correct/kfd.yaml
- test/data/e2e/validate/config/wrong/kfd.yaml
- test/data/e2e/validate/dependencies/correct/furyctl.yaml
- test/data/e2e/validate/dependencies/correct/kfd.yaml
- test/data/e2e/validate/dependencies/missing/kfd.yaml
- test/data/e2e/validate/dependencies/wrong/kfd.yaml
- test/data/expensive/common/data/kfd.yaml
- test/data/integration/v1.24.1/distro/kfd.yaml
- test/e2e/furyctl_test.go
Changelist:
- added a step in the validation process, to check if the bucket from the furyctl.yaml exists
- added terraform semver constraint support
needs https://github.com/sighupio/fury-distribution/pull/51
partially fixes #219 
closes #137
> Feat: added terraform state bucket validation

- cmd/create/cluster.go
- cmd/delete/cluster.go
- go.mod
- go.sum
- internal/apis/kfd/v1alpha2/eks/create/infrastructure.go
- internal/apis/kfd/v1alpha2/eks/creator.go
- internal/apis/kfd/v1alpha2/eks/deleter.go
- internal/apis/kfd/v1alpha2/eks/vpn.go
- internal/cluster/creator.go
- internal/cluster/deleter.go
> feat: vpn UX improvements

- cmd/legacy.go
- cmd/legacy/vendor.go
- cmd/root.go
- internal/legacy/dir.go
- internal/legacy/download.go
- internal/legacy/furyfile.go
- internal/legacy/package_url.go
- internal/legacy/provider_kind.go
Changelist:
- added legacy vendor command, command logic is taken from older furyctl with just minor refactoring to fix linting and removal of unused stuff
closes #309
> feat: added legacy vendor cmd

- internal/template/generator_test.go
- internal/template/mapper/mapper.go
- internal/template/mapper/mapper_test.go
- test/data/e2e/dump/template/complex-dry-run/furyctl.yaml
- test/data/e2e/dump/template/complex/furyctl.yaml
- test/data/e2e/validate/config/nodistro/furyctl.yaml
- test/data/e2e/validate/config/wrong/furyctl.yaml
- test/data/e2e/validate/dependencies/correct/furyctl.yaml
- test/data/e2e/validate/dependencies/missing/furyctl.yaml
- test/data/e2e/validate/dependencies/wrong/furyctl.yaml
> fix: converted file and env from object to string in template engine

- README.md
*SAFE TO MERGE PR*
Just added go report badge to readme:
[![Go Report Card](https://goreportcard.com/badge/github.com/sighupio/furyctl)](https://goreportcard.com/report/github.com/sighupio/furyctl)
> Add go report badge to readme

- configs/provisioners/cluster/eks/coredns.tf.tpl
- configs/provisioners/cluster/eks/variables.tf
- internal/apis/kfd/v1alpha2/eks/create/distribution.go
- internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
- internal/distribution/iac.go
Changelist:
- added furyctl config merge also on kubernetes phase
- added coredns patch on terraform phase kubernetes
- fixed on distribution ignore folders
partially fixes: #283
> feat: added coredns patch on phase kubernetes

- go.mod
- go.sum
> refactor(go.mod): reorder require sections

- go.mod
- go.sum
- internal/apis/kfd/v1alpha2/eks/create/infrastructure.go
- internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
- internal/apis/kfd/v1alpha2/eks/creator.go
- internal/apis/kfd/v1alpha2/eks/delete/infrastructure.go
- internal/apis/kfd/v1alpha2/eks/delete/kubernetes.go
- internal/apis/kfd/v1alpha2/eks/deleter.go
- internal/apis/kfd/v1alpha2/eks/tool.go
- internal/apis/kfd/v1alpha2/eks/vpn.go
- internal/dependencies/tools/test_data/furyctl.yaml
- test/data/e2e/create/cluster/data/furyctl.yaml
- test/data/e2e/create/cluster/data/schemas/public/ekscluster-kfd-v1alpha2.json
- test/data/e2e/create/config/default/data/expected-furyctl.yaml
- test/data/e2e/create/config/distro/templates/config/ekscluster-kfd-v1alpha2.yaml.tpl
- test/data/e2e/download/dependencies/v1.24.1/furyctl.yaml
- test/data/e2e/dump/template/complex-dry-run/furyctl.yaml
- test/data/e2e/dump/template/complex/furyctl.yaml
- test/data/e2e/validate/config/correct/furyctl.yaml
- test/data/e2e/validate/config/correct/schemas/public/ekscluster-kfd-v1alpha2.json
- test/data/e2e/validate/config/nodistro/furyctl.yaml
- test/data/e2e/validate/config/wrong/furyctl.yaml
- test/data/e2e/validate/config/wrong/schemas/public/ekscluster-kfd-v1alpha2.json
- test/data/e2e/validate/dependencies/correct/furyctl.yaml
- test/data/e2e/validate/dependencies/missing/furyctl.yaml
- test/data/e2e/validate/dependencies/wrong/furyctl.yaml
- test/data/expensive/create-complete/data/furyctl.yaml
- test/data/expensive/create-skip-infra/data/furyctl.yaml
- test/data/expensive/create-skip-kube/data/furyctl.yaml
- test/data/integration/v1.24.1/furyctl.yaml
Changelist:
- moved infrastructure.vpc.vpn to infrastructure.vpn
- fixed tests
> feat: initial update Vpc.Vpn -> Infrastructure.Vpn

- go.sum
- internal/apis/kfd/v1alpha2/eks/creator.go
- internal/x/slices/clean.go
> fix: don't ask VPN connection if cluster is public or public/private

- cmd/create/cluster.go
- cmd/delete/cluster.go
- cmd/validate/dependencies.go
- go.mod
- go.sum
- internal/apis/kfd/v1alpha2/eks/create/infrastructure.go
- internal/apis/kfd/v1alpha2/eks/tool.go
- internal/apis/tool.go
- internal/dependencies/tools/validator.go
- internal/dependencies/tools/validator_test.go
- internal/dependencies/validate.go
OpenVPN was required when the vpn section under infrastructure was filled, it should also be added that --vpn-auto-connect is true.
> feat: removed openvpn requirement when not using --vpn-auto-connect

- examples/furyctl.yaml
- internal/apis/kfd/v1alpha2/eks/delete/distribution.go
- internal/kubernetes/client.go
- internal/kubernetes/client_test.go
- internal/tool/kubectl/runner.go
> fix: delete resources with ns=all

- examples/furyctl.yaml
- go.mod
- internal/apis/kfd/v1alpha2/eks/creator.go
- internal/apis/kfd/v1alpha2/eks/deleter.go
- internal/apis/kfd/v1alpha2/eks/vpn.go
- internal/tool/awscli/runner.go
- internal/tool/furyagent/config.go
- internal/tool/furyagent/runner.go
- internal/tool/furyagent/runner_test.go
> feat: ovpn certs are created each time cluster create run

- cmd/create/cluster.go
- cmd/delete/cluster.go
- cmd/download.go
- cmd/download/dependencies.go
- cmd/validate.go
- cmd/validate/config.go
- cmd/validate/dependencies.go
- cmd/version.go
- internal/apis/kfd/v1alpha2/eks/vpn.go
This PR includes a series of improvements to the UX (from my POV), I'm open to discussion.
- Change VPN skip flag in create command to be consistent with the other flags.
- Improve flags and commands descriptions
- Improve some log messages
- Align description of flags between commands
> chore: UX improvements

- cmd/create/cluster.go
- cmd/create/config.go
- cmd/delete/cluster.go
- cmd/download/dependencies.go
- cmd/dump/template.go
- cmd/validate/config.go
- cmd/validate/dependencies.go
- internal/dependencies/tools/git.go
- internal/dependencies/tools/git_test.go
- internal/dependencies/tools/tool.go
- internal/dependencies/tools/tool_test.go
- internal/dependencies/tools/validator.go
- internal/dependencies/tools/validator_test.go
- internal/dependencies/validate.go
- internal/tool/git/runner.go
- internal/tool/git/runner_test.go
- internal/tool/runner.go
Changelist:
- added additional base requirements check in every command to check that 'git' is in $PATH
fixes #330
> feat: added git tool check

- automated-tests/e2e-tests/vsphere/cluster.tpl.yml
- automated-tests/integration/vsphere/cluster.yml
- automated-tests/integration/vsphere/tests.sh
- data/provisioners/cluster/vsphere/main.tf
- data/provisioners/cluster/vsphere/provision/all-in-one.yml
- data/provisioners/cluster/vsphere/variables.tf
- internal/cluster/configuration/vsphere.go
- internal/cluster/provisioners/vsphere/provisioner.go
- internal/configuration/templates.go
Because boundary became not used at all, is something that we don't need in the ansible setup, so I've removed the task from the Ansible.
> chore: removing useless Boundary setup from Ansible

- .drone.yml
- .rules/.golangci.yml
- Makefile
- README.md
- go.mod
- internal/analytics/event.go
- internal/analytics/tracker.go
- internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
- internal/template/model_test.go
- internal/template/node.go
- internal/x/kube/secret.go
- internal/x/kube/secret_test.go
- test/data/e2e/create/cluster/infrastructure/data/furyctl.yaml
- test/data/e2e/create/cluster/kubernetes/data/furyctl.yaml
- test/data/e2e/validate/dependencies/correct/furyctl.yaml
- test/e2e/furyctl_test.go
Changelist:
- upped from quay.io/sighup/golang:1.19.6 to quay.io/sighup/golang:1.20.4
> Chore: up golang version

- cmd/create/cluster.go
- internal/apis/kfd/v1alpha2/eks/create/distribution.go
- internal/apis/kfd/v1alpha2/eks/create/infrastructure.go
- internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
- internal/apis/kfd/v1alpha2/eks/creator.go
- internal/cluster/creator.go
- internal/cmd/cmdutil/flag.go
- internal/tool/ansible/runner.go
- internal/tool/awscli/runner.go
- internal/tool/furyagent/runner.go
- internal/tool/git/runner.go
- internal/tool/kubectl/runner.go
- internal/tool/kustomize/runner.go
- internal/tool/openvpn/runner.go
- internal/tool/runner.go
- internal/tool/runner_test.go
- internal/tool/terraform/runner.go
- internal/x/exec/cmd.go
- internal/x/exec/cmd_test.go
Closes #269.
- Added `--timeout` flag to `furyctl cluster create` command
> feat: add timeout flag

- go.mod
- go.sum
> Feat: support branches in distributionVersion field

- cmd/connect/openvpn.go
- internal/apis/kfd/v1alpha2/eks/create/distribution.go
- internal/apis/kfd/v1alpha2/eks/create/infrastructure.go
- internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
- internal/tool/terraform/runner.go
- internal/tool/terraform/runner_test.go
- update codebase to make it work with terraform 1.x modules
- fix: add output fake command for tf runner tests
> feature/upgrade terraform to 1.x

- internal/dependencies/tools/ansible.go
- internal/dependencies/tools/awscli.go
- internal/dependencies/tools/furyagent.go
- internal/dependencies/tools/kubectl.go
- internal/dependencies/tools/kustomize.go
- internal/dependencies/tools/openvpn.go
- internal/dependencies/tools/terraform.go
WARNING: this breaks furyctl users with arm64 os arch, terraform 0.15.4 does not have an arm64 build
closes https://github.com/sighupio/furyctl/issues/206
> Feat: tools download check for the user os architecture

- internal/apis/kfd/v1alpha2/distribution/creator.go
- internal/apis/kfd/v1alpha2/eks/creator.go
- internal/x/kube/secret.go
- internal/x/kube/secret_test.go
> feat: added store of kfd.yaml secret

- .goreleaser.yml
> feat: remove windows release

- .rules/.golangci.yml
- cmd/connect/openvpn.go
- cmd/create/cluster.go
- cmd/delete/cluster.go
- cmd/download/dependencies.go
- cmd/dump/template.go
- cmd/root.go
- cmd/validate/dependencies.go
- test/e2e/furyctl_test.go
Hi all, this PR addresses the issue #391 and adds the flag `--outdir` to use a different folder instead of the homeDir of the user.
> Feature: flag outdir

- cmd/root.go
- internal/analytics/tracker.go
> chore: removed errors and general debug logging from mixpanel

- internal/template/mapper/mapper.go
- internal/template/mapper/mapper_test.go
> feat: make furyctl ${env://} and ${file://} concatenable

- internal/template/mapper/mapper.go
- internal/template/mapper/mapper_test.go
- internal/x/io/fs.go
> feat: support slice of strings and slice of map

- internal/template/mapper/mapper.go
- internal/template/mapper/mapper_test.go
> fix: test and fix dynamic config with yaml.v2 structure

- cmd/create/cluster.go
- internal/apis/kfd/v1alpha2/common/create/plugins.go
- internal/apis/kfd/v1alpha2/distribution/create/distribution.go
- internal/apis/kfd/v1alpha2/distribution/creator.go
- internal/apis/kfd/v1alpha2/eks/create/distribution.go
- internal/apis/kfd/v1alpha2/eks/creator.go
- internal/apis/kfd/v1alpha2/onpremises/create/distribution.go
- internal/apis/kfd/v1alpha2/onpremises/create/kubernetes.go
- internal/cluster/phase.go
- internal/dependencies/tools/helm.go
- internal/dependencies/tools/helmfile.go
- internal/dependencies/tools/tool.go
- internal/tool/helm/runner.go
- internal/tool/helmfile/runner.go
- internal/tool/runner.go
Closes #428.
- Add plugin support using helmfile
Merge after https://github.com/sighupio/fury-distribution/pull/124 and update `go.mod`.
> feat: add plugins using helmfile

- cmd/apply.go
- cmd/diff.go
- cmd/errors.go
- cmd/root.go
- internal/apis/kfd/v1alpha2/distribution/creator.go
- internal/apis/kfd/v1alpha2/eks/creator.go
- internal/apis/kfd/v1alpha2/onpremises/creator.go
- internal/cluster/creator.go
- internal/diffs/checker.go
> feat: added diff cmd

- internal/apis/kfd/v1alpha2/eks/create/preflight.go
- internal/apis/kfd/v1alpha2/eks/tool.go
- internal/dependencies/tools/validator_test.go
- feat: autocreate the terraform state bucket before starting the apply action
> Introduce terraform state bucket creation in furyctl create cluster

- cmd/apply.go
- cmd/delete/cluster.go
- cmd/diff.go
- cmd/errors.go
- configs/upgrades/ekscluster/1.25.8-1.25.9/pre-infrastructure.sh.tpl
- configs/upgrades/onpremises/1.25.9-1.26.4/pre-kubernetes.sh.tpl
- configs/upgrades/onpremises/1.26.4-1.27.0/pre-kubernetes.sh.tpl
- internal/apis/kfd/v1alpha2/common/create/preupgrade.go
- internal/apis/kfd/v1alpha2/distribution/creator.go
- internal/apis/kfd/v1alpha2/eks/creator.go
- internal/apis/kfd/v1alpha2/onpremises/creator.go
- internal/cluster/creator.go
> feat: add --upgrade-path-location flag

- internal/distribution/iac.go
> feat: fix dump template command

- README.md
- configs/patches/v1.25.9/templates/distribution/manifests/dr/patches/eks-velero.yml.tpl
- configs/patches/v1.26.4/templates/distribution/manifests/dr/patches/eks-velero.yml.tpl
- configs/patches/v1.27.0/templates/distribution/manifests/dr/patches/eks-velero.yml.tpl
- configs/patches/v1.27.1/templates/distribution/manifests/dr/patches/eks-velero.yml.tpl
- internal/apis/kfd/v1alpha2/distribution/create/distribution.go
- internal/apis/kfd/v1alpha2/onpremises/create/distribution.go
This PR adds a patch to fix the behaviour of the new DR v2.2.0 module for the latest distro versions
> Fix: velero eks on newer versions template patch

- internal/apis/kfd/v1alpha2/ekscluster/create/preflight.go
- internal/apis/kfd/v1alpha2/ekscluster/creator.go
- internal/apis/kfd/v1alpha2/kfddistribution/create/preflight.go
- internal/apis/kfd/v1alpha2/kfddistribution/creator.go
- internal/apis/kfd/v1alpha2/onpremises/create/preflight.go
- internal/apis/kfd/v1alpha2/onpremises/creator.go
- internal/apis/kfd/v1alpha2/reducer.go
- internal/state/store.go
- internal/state/store_test.go
- internal/template/config.go
- internal/template/config_test.go
- internal/x/kube/secret.go
- internal/x/kube/secret_test.go
- improve migrations logging messages, hide irrelevant ones from INFO and move them to DEBUG
- add rendered config to the cluster secret, use it instead of the regular one when checking for diffs
> feat: diffs improvements

- configs/patches/v1.26.5/templates/distribution/scripts/pre-apply.sh.tpl
- configs/patches/v1.27.2/templates/distribution/scripts/pre-apply.sh.tpl
- configs/patches/v1.27.3/templates/distribution/scripts/pre-apply.sh.tpl
fixes #487 along with https://github.com/sighupio/fury-distribution/pull/187
> fix: issue #487

- cmd/apply.go
- cmd/create/config.go
- cmd/delete/cluster.go
- cmd/diff.go
- cmd/download/dependencies.go
- cmd/dump/template.go
- cmd/validate/config.go
- cmd/validate/dependencies.go
- internal/dependencies/download.go
- internal/distribution/download.go
- internal/x/net/client.go
- test/expensive/ekscluster/furyctl_test.go
- test/expensive/kfddistribution/furyctl_test.go
- test/expensive/onpremises/furyctl_test.go
- test/utils/testutils.go
> feat: move binaries and cache to outdir if present

- cmd/create/config.go
- test/data/e2e/create/config/distro/schemas/public/ekscluster-kfd-v1alpha2.json
> feat: improve UX in config creations sub cmd

- cmd/get.go
- cmd/get/kubeconfig.go
- cmd/root.go
- internal/apis/kfd/v1alpha2/ekscluster/init.go
- internal/apis/kfd/v1alpha2/ekscluster/kubeconfig_getter.go
- internal/apis/kfd/v1alpha2/kfddistribution/init.go
- internal/apis/kfd/v1alpha2/kfddistribution/kubeconfig_getter.go
- internal/apis/kfd/v1alpha2/onpremises/init.go
- internal/apis/kfd/v1alpha2/onpremises/kubeconfig_getter.go
- internal/cluster/kubeconfig_getter.go
- internal/x/go-getter/file_getter.go
closes [#415](https://github.com/sighupio/product-management/issues/415)
> feat: added get kubeconfig sub command

- README.md
> docs(readme): align readme with latest versions

- Makefile
> fix: add envs for e2e tests

- cmd/create/pki.go
improve help message and formatting for the new create pki command
> chore: improve create pki help messages

- cmd/get/kubeconfig.go
Fixes an issue with path interpolations, where relative paths would not be converted to absolute paths within the `get kubeconfig` subcommand
> fix(get-kubeconfig): retrieve absolute path to config file

- internal/distribution/compatibility.go
- internal/distribution/compatibility_test.go
> fix: fix compatibility for other kinds

- configs/patches/v1.27.9/templates/kubernetes/onpremises/hosts.yaml.tpl
- configs/patches/v1.28.4/templates/kubernetes/onpremises/hosts.yaml.tpl
- configs/patches/v1.29.4/templates/kubernetes/onpremises/hosts.yaml.tpl
- Added patches related to https://github.com/sighupio/fury-distribution/pull/271.
> fix: add custom registry patches

- configs/upgrades/ekscluster/1.27.8-1.27.9/pre-distribution.sh.tpl
- configs/upgrades/ekscluster/1.27.9-1.28.4/pre-distribution.sh.tpl
- configs/upgrades/ekscluster/1.28.3-1.28.4/pre-distribution.sh.tpl
- configs/upgrades/ekscluster/1.28.4-1.29.4/pre-distribution.sh.tpl
- configs/upgrades/ekscluster/1.29.3-1.29.4/pre-distribution.sh.tpl
- configs/upgrades/kfddistribution/1.27.8-1.27.9/pre-distribution.sh.tpl
- configs/upgrades/kfddistribution/1.27.9-1.28.4/pre-distribution.sh.tpl
- configs/upgrades/kfddistribution/1.28.3-1.28.4/pre-distribution.sh.tpl
- configs/upgrades/kfddistribution/1.28.4-1.29.4/pre-distribution.sh.tpl
- configs/upgrades/kfddistribution/1.29.3-1.29.4/pre-distribution.sh.tpl
> fix: add missing upgrade paths

- cmd/apply.go
- cmd/completion.go
- cmd/create.go
- cmd/create/config.go
- cmd/dump.go
- cmd/dump/template.go
- cmd/get.go
- cmd/root.go
- internal/apis/kfd/v1alpha2/ekscluster/create/preflight.go
- internal/apis/kfd/v1alpha2/ekscluster/delete/preflight.go
- internal/apis/kfd/v1alpha2/kfddistribution/create/preflight.go
- internal/apis/kfd/v1alpha2/kfddistribution/delete/preflight.go
- internal/apis/kfd/v1alpha2/onpremises/create/kubernetes.go
- internal/apis/kfd/v1alpha2/onpremises/create/preflight.go
- internal/apis/kfd/v1alpha2/onpremises/delete/kubernetes.go
- internal/apis/kfd/v1alpha2/onpremises/delete/preflight.go
- Improve help messages adding missing subcommands in the main summary and details where missing.
- Fix some outdate information in help messages.
- Improve the redaction of some of the help messages.
- Improve some log messages that were giving information that the user does not care about.
> chore(ux): improve help messages and some logs

- docs/development/development.md
- Added new docs section with development faq
> docs: add development faq docs

- configs/patches/v1.29.7/templates/distribution/scripts/apply.sh.tpl
- configs/patches/v1.30.2/templates/distribution/scripts/apply.sh.tpl
- configs/patches/v1.31.0/templates/distribution/scripts/apply.sh.tpl
- configs/patches/v1.31.1/templates/distribution/scripts/apply.sh.tpl
This PR adds some distro patches to [backport this](https://github.com/sighupio/distribution/pull/399) to previous versions of the SIGHUP Distribution.
This backport renders the `apply.sh` script compatible with POSIX.
Nothing.
Nothing.
Nothing.
> fix: add distro patches for issue #399 in distro

- internal/lockfile/lockfile.go
- Save the PID of the current furyctl process in the lockfile.
- Print it out the saved PID if the lock file is still present.
Relates: improves on #599
Show the user the last PID of furyctl when the lockfile is still present, so they can check if the process is still running or the lockfile can safely be removed.
The new error message looks like this:
```
ERRO error while verifying lock file /var/folders/lb/zscvwt_s6fx6qdrfv4g51dsc0000gn/T/furyctl-multipass: lock file exists. Last execution finished abnormally or there may be another instance of furyctl running with PID 70457
```
None
None
> feat(lockfile): save PID of running process

- cmd/create/pki.go
Fixing the PKI create command returning an unexpected error after creating etcd or controlplane certs.
Closes: issue #622
Relates:
Adding the message return for each switch cases.
Tests performed:
- Creating certs for both controlplane and etcd (`furyctl create pki`)
- Creating certs only for the controlplane (`furyctl create pki -c`)
- Creating certs only for etcd (`furyctl create pki -e`)
`furyctl` version:
```bash
furyctl version
buildTime: 2025-06-16T14:25:53Z
gitCommit: 1345b667321d6dfe954adc37afab8995923ef7e1
goVersion: go1.23.2
osArch: amd64
version: 0.32.5
```
> fix(cmd): Fix PKI create command
