README.md
cmd/config.go
go.mod
main.go

Github urls changed from `.../sighup-io/...` to `.../sighupio/...`
Bonus: I have found a little mistake in the installation instructions, the extension of the downloaded binary was missing.

Github urls fixed

---

Furyfile.yml
README.md
cmd/config.go
cmd/download.go
cmd/root.go
go.mod
go.sum

I'm using the keys in the "versions" map as a prefix to decide if a module has to use the global version specified. I was thinking about using regexes, but sounded overkill.
You can find an updated and commented example in the Readme and a Furyfile in the root of the repo.

Furyfile overridable "global versions" for roles/modules/bases

---

DEVELOPER.md
README.md
cmd/download.go
cmd/init.go
cmd/root.go
cmd/vendor.go

Hi team!
This PR implements: https://github.com/sighupio/poc-fury-distribution/issues/1
**It can not be merged until we open the https://github.com/sighupio/poc-fury-distribution/ repository**, but you can see what's the idea ;)
In this PR you can find:
- Added `furyctl init --version XYZ` command with the `--version flag configured as required`
- Renamed `furyctl install` into `furyctl vendor`.
- ~~BUGFIX: `furyctl printDefault` used log instead of fmt causing an incorrect Furyfile.yml output if `furyctl printDefault > Furyfile.yml` executed.~~
- Removed `furyctl printDefault`
Thanks for your time!

Init Distribution

---

Furyfile.yml
cmd/config.go

Due to a bug discovered during the provisioning of module velero with @simonemex  and @lnovara   that has. a subdir of multiple path, here it is the patch for this bug. Now the function will handle whatever hierarchy level of subdir will exist in the repo

fix depth subpath bug

---

README.md
cmd/root.go

There was a bogus `--toggle` flag that did nothing, probably copy&pasted from an example. This PR removes it.

Dropped unused 'toggle' boolean flag

---

cmd/download.go
go.mod

Hi everyone 👋 !
As @nutellinoit  said in a previous issue, there is currently a problem with public modules that embed also the `.git` subfolders. 
The current PR resolves the following misbehaviors: 
1. errors when you want to re-run a furyctl vendor multiple times (more than 1 actually :D ) 
2. remove automatically `.git` subfolder from the public modules that contain the `.git` subfolder
Basically now the final behavior is the same of the fury module. 
Let me know if everything looks good for you!

now the download can be repeated without errors

---

cmd/config.go
cmd/download.go
cmd/vendor.go

Hi team!
I added a little flag on the furyctl vendor command ~`--filter`~ `--prefix` to add a prefix on the modules i want to update, eg: ~`furyctl vendor --filter dr/velero`~  `furyctl vendor --prefix dr/velero`.
This can useful when we do stack upgrades.

Little flag to filter updates in Furyfile

---

cmd/bootstrap.go
cmd/cluster.go
go.mod
go.sum
internal/bootstrap/bootstrap.go
internal/cluster/cluster.go
pkg/terraform/terraform.go

Add `--reconfigure` flag.
It enables backend reconfiguration on demand. Useful in a scenario where you update the executor version (terraform).

Implement reconfigure flag

---

data/provisioners/cluster/eks/variables.tf
internal/cluster/configuration/eks.go
internal/cluster/provisioners/eks/provisioner.go
internal/configuration/config_test.go
internal/configuration/templates.go

This PR enables the possibility to specify from 1 to n number of DMZ CIDR ranges added in the cloud installer v1.5.0

Enable v1.5.0 feature in eks cluster provisioner

---

data/provisioners/cluster/vsphere/furyagent/.gitattributes

This will be used to encrypt the content of furyagent/pki folder, which contains etcd and master certificates for kubernetes.

Creating furyagent/.gitattributes

---

README.md
cmd/completion.go
cmd/config.go
cmd/root.go
cmd/vendor.go

This MR addresses issue #3. The cobra generator was used to auto-generate the completion scripts. The configuration to add the completion scripts to the shell configurations will be available on running the command `furyctl completion -h` as follows:
```bash
To load furyctl completions:
Bash:
$ source <(furyctl completion bash)
$ furyctl completion bash > /etc/bash_completion.d/furyctl
$ furyctl completion bash > /usr/local/etc/bash_completion.d/furyctl
Zsh:
$ echo "autoload -U compinit; compinit" >> ~/.zshrc
$ furyctl completion zsh > "${fpath[1]}/_furyctl"
fish:
$ furyctl completion fish | source
$ furyctl completion fish > ~/.config/fish/completions/furyctl.fish
PowerShell:
PS> furyctl completion powershell | Out-String | Invoke-Expression
PS> furyctl completion powershell > …
```

Adds (ba|z|fi)sh autocomplete for furyctl

---

.drone.yml
automated-tests/e2e-tests/aws-eks/cluster.tpl.yml
automated-tests/e2e-tests/gcp-gke/cluster.tpl.yml
automated-tests/e2e-tests/vsphere/.gitignore
automated-tests/e2e-tests/vsphere/tests-destroy.sh
automated-tests/e2e-tests/vsphere/tests.sh
automated-tests/integration/aws-eks/cluster.yml
automated-tests/integration/gcp-gke/cluster.yml
data/provisioners/cluster/eks/main.tf
data/provisioners/cluster/eks/variables.tf
data/provisioners/cluster/gke/main.tf
data/provisioners/cluster/gke/variables.tf
go.mod
go.sum
internal/cluster/configuration/eks.go
internal/cluster/configuration/gke.go
internal/cluster/provisioners/eks/provisioner.go
internal/cluster/provisioners/gke/provisioner.go
internal/configuration/assets/eks-cluster.yml
internal/configuration/config_test.go
internal/configuration/templates.go

This PR includes a couple of features (to be released) from the cloud-installers (eks, gke, aks).
- os: Specify the operating system to use on **eks** or **gke**.
- targetGroups: Specify the target group id to the instances of a node_pool so it can be linked to a different LB in **eks**.
I am marking this PR as WIP because first, the following PR has to be reviewed and merged:
- https://github.com/sighupio/fury-gke-installer/pull/20
- https://github.com/sighupio/fury-aks-installer/pull/9
- https://github.com/sighupio/fury-eks-installer/pull/25
In addition, I had to decouple the cluster destroy phase on vsphere because of the lack of stability in the environment. 
Pipeline seems to be working: https://ci.sighup.io/sighupio/furyctl/447/2/11 (e2e included)

WIP: Including new features to cluster-self provisioning

---

Makefile
cmd/download.go

In the event of a wrong supplied tag, furyctl removes the Furyfile.yml.

[BUGFIX] don't delete Furyfile if wrong KFD --version tag is supplied

---

README.md

Hi, this PR fixes a typo in the `README.md` file about the `vendor` command [HTTP flag](https://github.com/sighupio/furyctl/blob/master/cmd/vendor.go#L16) (`-H`).
Signed-off-by: Massimiliano Giovagnoli <me@maxgio.it>

docs(readme.md): fix typo in https flag

---

internal/template/generator.go
internal/template/model.go

load a `_helpers.tpl` file if exists and load it together with the temlpate to be rendered, allowing to define helper functions in the template logic.
This allows for example to have common logic shared between template files, for example, e function to get the ingress class.
Please feel free to modify the code as you wish

feat(template): load _helpers.tpl together with the template

---

cmd/download.go

After seeing the reaction of a user that is not familiar with Fury on the WARN messages thrown by the fallback logic in the vendor command, I believe is better to downgrade them to INFO to avoid alarming the user unnecessary, at least until we decide to move on with the renaming.

fix(vendor): downgrade repository fallaback message to Info

---

internal/cluster/configuration/eks.go
internal/cluster/provisioners/eks/provisioner.go
internal/configuration/assets/eks-cluster.yml
internal/configuration/config_test.go
internal/configuration/templates.go

This change requires the following PR on `fury-eks-installer` to work: https://github.com/sighupio/fury-eks-installer/pull/40
Together, the two changes allow the user to (optionally) specify a custom log retention days number, like in the following snippet:
```
kind: Cluster
metadata:
name: demo
provisioner: eks
spec:
version: "1.22"
logRetentionDays: 30
network: "vpc-1"
...
```

Add EKS LogRetentionDays

---

README.md
automated-tests/e2e-tests/aws-eks/cluster.tpl.yml
automated-tests/integration/aws-eks/cluster.yml
data/provisioners/bootstrap/aws/main.tf
data/provisioners/cluster/eks/main.tf
data/provisioners/cluster/eks/output.tf
data/provisioners/cluster/eks/variables.tf
internal/cluster/configuration/eks.go
internal/cluster/provisioners/eks/provisioner.go
internal/configuration/assets/eks-cluster.yml
internal/configuration/config_test.go
internal/configuration/templates.go

- add missing mappings for EKS  ClusterLogRetentionDays parameter
- expose new parameter for EKS NodePoolsLaunchKind
- Enforce that NodePoolsLaunchKind is set and not defaulted to avoid node pools rollouts
- improve EKS cluster console messages
- update test to consider the new parameters
- update docs to prepare for releasing v0.9.0
- fix Kubeconfig generation. v1alpha1 is deprecated.
BREAKING CHANGE: there are two 2 parameters in the configuration file, ClusterLogRotationDays can be left as default in most cases, but users need to set explicitly the new NodePoolsLaunchKind parameter, because migrating to the new kind requires a rollout of all the existing node pools.

feat!(eks): add support for EKS Installer v1.10.0

---

cmd/create/cluster.go
cmd/delete/cluster.go
internal/apis/kfd/v1alpha2/eks/create/distribution.go
internal/apis/kfd/v1alpha2/eks/create/infrastructure.go
internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
internal/apis/kfd/v1alpha2/eks/delete/distribution.go
internal/apis/kfd/v1alpha2/eks/delete/infrastructure.go
internal/apis/kfd/v1alpha2/eks/delete/kubernetes.go
internal/cluster/phase.go
test/e2e/furyctl_test.go
test/expensive/furyctl_test.go

Changelist:
- added an error when trying to use an unsupported phase flag in create/delete cluster command:
`ERRO error while parsing flag: phase: options are: infrastructure, kubernetes, distribution`
- added an error when trying to use an unsupported skip-phase flag in create cluster command:
`ERRO error while parsing flag: skip-phase: unsupported phase, options are: infrastructure, kubernetes, distribution`
- added an error when trying to use phase and skip-phase flag together:
`ERRO error while parsing flag: skip-phase: cannot use together with phase flag`
- refactored "infrastructure", "kubernetes", "distribution" to use enums instead

feat: handle unsupported phases

---

internal/dependencies/download.go

Furyctl should properly handle private and non-existing repositories as done in the furyctl legacy version

Handling private or non exist modules

---

cmd/create/cluster.go
cmd/delete/cluster.go
internal/apis/kfd/v1alpha2/eks/delete/distribution.go
internal/apis/kfd/v1alpha2/eks/delete/infrastructure.go
internal/apis/kfd/v1alpha2/eks/delete/kubernetes.go
internal/tool/kubectl/runner.go
internal/tool/terraform/runner.go

Changelist:
- added --dry-run to cluster delete phases
infrastructure(dry-run): output plan -destroy
kubernetes(dry-run): output plan -destroy
distribution(dry-run): output plan -destroy and kubectl delete --dry-run, plus a list of resources deleted from the cluster, regardless of the manifests built from the template
example output of distribution(dry-run):

feat: added dry run to cluster delete

---

cmd/download.go
cmd/vendor.go

After https://github.com/sighupio/fury-getting-started/issues/25 (thanks @raclepoulpe) we discovered a bug in the go-getter's library that occurs when the passed URL has whitespaces in it. In this case, the GITHUB_TOKEN erroneously presented a whitespace injected into the OAuth URI to be given to the go-getter's client. This PR is intended to partially mitigate this problem by warning the user with a warning message.

chore: check github token whitespaces, improve logrus format

---

internal/apis/kfd/v1alpha2/eks/creator.go

Changelist:
- added warn message to tell the user to make sure the cluster is reachable when running phase kubernetes
closes #166

Feat: Warn the user about connectivity when running kubernetes phase

---

internal/distribution/download.go
internal/x/net/hashicorp.go
test/e2e/furyctl_test.go

Changelist:
- replaced missing `kfd.yaml` message with info about unsupported KFD version when running with or without --distro-location flag
closes #165

Feat: UX improvement about unsupported KFD version

---

cmd/create/cluster.go
cmd/create/config.go
cmd/delete/cluster.go
cmd/download/dependencies.go
cmd/validate/config.go
cmd/validate/dependencies.go
internal/dependencies/download.go
internal/distribution/download.go

Changelist:
- added depth=1 to every go-getter url
⚠️ needs #171 to be merged
NOTE: this is possibly breaking, now it's not possible to specify a commit hash as a ref
closes #169

Feat: add depth=1 to go-getter urls

---

cmd/create/cluster.go
cmd/delete/cluster.go
cmd/root.go
internal/tool/terraform/runner.go
internal/x/exec/cmd.go
internal/x/logrus/config.go

Changelist:
- refactor cluster delete flags as already done in cluster create
- use no-tty in logrus init function
- add support to terraform init && delete to no-tty (-no-color)
fixes #191

Feat: support no-tty in external commands

---

internal/x/bytes/transform.go
internal/x/bytes/transform_test.go
internal/x/exec/cmd.go
internal/x/io/multiwritertransform.go
internal/x/io/multiwritertransform_test.go
internal/x/logrus/config.go

ChangeList:
-  introduced MultiWriterTransform: adds the capability of changing the input []byte via chained functions before writing to multiple io.Writer instances
- added StripColor, ToJSONLogFormat transform functions to remove colors from buffer strings and encode them to a JSON log format
- refactor cmd to use MultiWriterTransform instead of MultiWriter
log format: `{"level":<log level>, "action":<command executed>, "msg":<command output>, "time":<timestamp>}`
example output:
`{"level":"debug","action":"terraform plan -no-color -out plan/terraform.plan","msg":"\n─────────────────────────────────────────────────────────────────────────────\n\nSaved the plan to: plan/terraform.plan\n\nTo perform exactly these actions, run the following command to apply:\n    terraform apply …

Feat: added json logs to external tools

---

.goreleaser.yml

Add `arm64` architecture when creating release packages

Create arm64 release packages

---

internal/dependencies/envvars/validator.go
test/e2e/furyctl_test.go

Changelist:
- added support to AWS_PROFILE
- modified error message when validating environment variables
missing credentials:
missing AWS_DEFAULT_REGION ( required https://github.com/hashicorp/terraform-provider-aws/issues/7750 ):
fixes #234

Feat: added support to AWS_PROFILE

---

internal/apis/kfd/v1alpha2/eks/create/distribution.go
internal/apis/kfd/v1alpha2/eks/creator.go

Changelist:
- removed cluster reachability warning when running --dry-run without --phase
- phase distribution will not return an error when terraform plan fails in --dry-run
closes #237

Chore: removed warning about cluster reachability when in dry-run

---

README.md
cmd/dump/template.go
internal/distribution/iac.go
internal/distribution/manifest.go
test/data/e2e/dump/template/complex-dry-run/kfd.yaml
test/data/e2e/dump/template/complex/kfd.yaml
test/data/e2e/dump/template/distribution-yaml-no-data-property/kfd.yaml
test/data/e2e/dump/template/no-distribution-yaml/furyctl.yaml
test/data/e2e/dump/template/no-furyctl-yaml/kfd.yaml
test/data/e2e/dump/template/simple-dry-run/kfd.yaml
test/data/e2e/dump/template/simple/kfd.yaml
test/e2e/furyctl_test.go

Changelist:
- added --distro-location --config --out-dir --skip-validation flag to dump template cmd
- moved cmd logic to the distribution package
fixes #270

feat: rework furyctl dump template cmd

---

data/provisioners/cluster/eks/variables.tf
internal/cluster/configuration/eks.go
internal/cluster/provisioners/eks/provisioner.go
pkg/analytics/analytics.go

Implements the new feature in the fury-eks-installer that allows to specify containerd as container runtime interface for clusters that still default to dockershim
> **Warning**
> Needs a release of the eks-installer with sighupio/fury-eks-installer#50 merged first

feature: adds containerRuntime parameter to EKS node pools

---

internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
internal/apis/kfd/v1alpha2/eks/delete/kubernetes.go

Changelist:
- fix bug on vpc connectivity check using env var instead of .spec.region

fix: missing region from vpc connectivity check

---

cmd/connect.go
cmd/connect/openvpn.go
cmd/root.go

Closes #312.
- Added `connect openvpn` command to start OpenVPN in foreground.
I experimented another version with OpenVPN in daemon mode but the `Process` returned by Go doesn't have the correct `Pid`, it's always some ID behind so obviously you can't kill the process with the `disconnect openvpn` command. I'm still trying to figure out why.

feat: add connect openvpn command

---

.drone.yml
.goreleaser.yml
README.md
data/provisioners/bootstrap/aws/main.tf
data/provisioners/bootstrap/gcp/main.tf
data/provisioners/cluster/eks/main.tf

As per title, this updates the installer on the legacy version and removes the brew step on goreleaser

Feat: update installer to fix spot with launch templates

---

internal/apis/kfd/v1alpha2/eks/create/infrastructure.go
internal/apis/kfd/v1alpha2/eks/create/kubernetes.go

Changelist:
- added uniq on allowedClusterEndpointPrivateAccessCIDRs slice in order to remove duplicates
- added uniq on ssh AllowedFromCidrs slice
- added uniq on AdditionalFirewallRules CidrBlocks slice

Fix: remove duplicates on cidrs

---

cmd/apply.go
cmd/completion.go
cmd/create.go
cmd/create/config.go
cmd/download.go
cmd/dump.go
cmd/root.go
internal/apis/kfd/v1alpha2/eks/vpn/connector.go
internal/tool/furyagent/runner.go

The goal of this PR is to prepare the ground for the actual cluster upgrade feature by making sure we treat the cluster folder as fully ephemeral and by creating the `cluster create` command alias `apply`
Closes https://github.com/sighupio/furyctl/issues/438.
Closes https://github.com/sighupio/furyctl/issues/437.

feat: cluster upgrade preparations

---

README.md
docs/COMPATIBILITY_MATRIX.md
internal/x/io/fs.go
internal/x/io/fs_test.go

Given an eks cluster with vpn enabled, terraform gives this error when running `--phase infrastructure`
```
Error: External Program Lookup Failed
with module.vpn[0].data.external.os,
on .terraform/modules/vpn/data.tf line 6, in data "external" "os":
6:   program = ["${path.module}/bin/os.sh"]
```
Files downloaded to the cache folder do not preserve permissions
downloaded files:
```
drwxr-xr-x   7 x  x   224B Feb 21 14:23 .
drwxr-xr-x  11 x  x   352B Feb 21 14:23 ..
-rwxr-xr-x   1 x  x    38M Feb 21 14:23 furyagent-darwin-amd64
-rwxr-xr-x   1 x  x    38M Feb 21 14:23 furyagent-darwin-arm64
-rwxr-xr-x   1 x  x    34M Feb 21 14:23 furyagent-linux-amd64
-rwxr-xr-x   1 x  x    33M Feb 21 14:23 furyagent-linux-arm64
-rwxr-xr-x   1 x  x   144B Feb 21 14:23 os.sh
```
cached files:
```
drwxr-xr-x …
```

bugfix: cache preserve file permissions

---

internal/parser/config.go
internal/parser/config_test.go
internal/template/mapper/mapper.go

This feature ad a new "dynamic value" for string interpolation the name `path` that converts a relative path to absolute.
NOTE: This feature can replace the string regex replacer that converts any string that starts with `./` as absolute.
Secret generator with files:
```yaml
customPatches:
secretGenerator:
- name: my-secret
namespace: default
type: kubernetes.io/tls
files:
- tls.crt={path://./certs/tls.crt}
- tls.key={path://./certs/tls.key}
```

Add support to relative paths with {path://} dynamic value

---

cmd/apply.go
cmd/create/config.go
cmd/delete/cluster.go
cmd/diff.go
cmd/download/dependencies.go
cmd/dump/template.go
cmd/validate/config.go
cmd/validate/dependencies.go
internal/cmd/cmdutil/flag.go
internal/distribution/download.go
internal/distribution/download_test.go
test/utils/testutils.go

usage: `--distro-patches go-getter/compatible/path`
Within the location, the folders must have the target KFD version as name (e.g. v1.29.0) and the contents should be compatible with those from the https://github.com/sighupio/fury-distribution repository.
closes #503

feat: added --distro-patches flag

---

cmd/apply.go
cmd/diff.go
internal/apis/kfd/v1alpha2/ekscluster/create/distribution.go
internal/apis/kfd/v1alpha2/ekscluster/create/infrastructure.go
internal/apis/kfd/v1alpha2/ekscluster/create/kubernetes.go
internal/apis/kfd/v1alpha2/ekscluster/creator.go
internal/apis/kfd/v1alpha2/kfddistribution/create/distribution.go
internal/apis/kfd/v1alpha2/kfddistribution/creator.go
internal/apis/kfd/v1alpha2/onpremises/create/distribution.go
internal/apis/kfd/v1alpha2/onpremises/create/kubernetes.go
internal/apis/kfd/v1alpha2/onpremises/creator.go
internal/cluster/creator.go
internal/cluster/phase.go
internal/upgrade/storedecorator.go

feat: added --post-apply-phases flag

---

internal/lockfile/lockfile.go

make the error message when the lock file exists more user friendly. Explaining what does it mean when the file already exists.
Before:
After:

chore(lockfile): improve error message

---

README.md
cmd/get.go
cmd/get/upgrade-paths.go
docs/upgrades/kfd/README.md
internal/apis/kfd/v1alpha2/common/create/preupgrade.go

Add a new command to list all the available upgrade paths known by furyctl for a specific cluster `kind` and `version`.
`kind` and `version` will be read from the furyctl.yaml file and can be overriden with a flag if wanted.
Overriding both flags skips downloading the distribution and all the validation steps and works entirely locally.
Examples:
```bash
❯ yq '.spec.distributionVersion' furyctl.yaml
v1.29.3
❯ yq '.kind' furyctl.yaml
OnPremises
❯ furyctl get upgrade-paths
INFO Downloading distribution...
INFO Compatibility patches applied for v1.29.3
INFO Validating configuration file...
INFO Downloading dependencies...
INFO Validating dependencies...
INFO There are no upgrade paths available for version 1.29.3 of kind OnPremises
❯ furyctl get upgrade-paths --from v1.27.4
INFO Downloading …
```

feat: get ugprade-paths command

---

cmd/get/kubeconfig.go

fix: fix get kubeconfig command

---

cmd/get/kubeconfig.go
cmd/get/upgrade-paths.go
cmd/renew/certificates.go
cmd/root.go
internal/apis/kfd/v1alpha2/ekscluster/kubeconfig_getter.go
internal/apis/kfd/v1alpha2/kfddistribution/kubeconfig_getter.go
internal/apis/kfd/v1alpha2/onpremises/certificates_renewer.go
internal/apis/kfd/v1alpha2/onpremises/kubeconfig_getter.go
internal/cluster/certificates_renewer.go
internal/cluster/kubeconfig_getter.go

Fixed `get kubeconfig`, `get upgrade-paths` and `renew certificates` commands.

fix: fix outdir and workdir on commands

---

configs/patches/v1.27.9/templates/distribution/manifests/auth/secrets/basic-auth.yml.tpl
configs/patches/v1.28.4/templates/distribution/manifests/auth/secrets/basic-auth.yml.tpl
configs/patches/v1.29.4/templates/distribution/manifests/auth/secrets/basic-auth.yml.tpl

Add compatibility patch for Hubble Ingress when using basic auth as auth provider on KFD versions 1.27.9, 1.28.4, and 1.29.4.
Reference: https://github.com/sighupio/fury-distribution/pull/277

feat(patches): add compatibility patch for hubble ingress basic auth

---

internal/apis/kfd/v1alpha2/ekscluster/common/distribution.go

- Added missing `spec.distribution.modules.ingress.certManager.clusterIssuer.route53.hostedZoneId` on the EKS private schema by reading it from the Terraform outputs.
- Region is always eu-west-1 (is this ok?).
Closes #https://github.com/sighupio/fury-distribution/issues/134.

fix: set clusterissuer route53 zone id by reading terraform outputs

---

internal/distribution/compatibility.go
internal/distribution/compatibility_test.go

This PR solves a small bug where `furyctl apply` commands with the OnPremises provider and version 1.30.1  give a warning about v1.30.1 being unsupported, when it's not the case.
This bug appears only with the OnPremises provider, while EKSCluster and KFDDistribution do not show this issue.
Closes: #565 
The change is a rather small one, adjusting the `max130Version` to the correct one in the code block that does the compatibility checks for the OnPremises provider. I also added relative unit tests to verify this behaviour.
None.
N/A

fix(compatibility): use the right max130Version for OnPremises

---

cmd/create/config.go

Fix example in `furyctl create config` command help, the version needs to start with `v`. Otherwise you'll get an error.
Closes: #573
See Summary and linked issue.
None
None

chore(cmd): fix create config example command

---

internal/dependencies/tools/kustomize.go
internal/tool/kustomize/runner.go

This follows the PR on fury-distribution to allow to update `kustomize` to version 5.6.0.
Relates: https://github.com/sighupio/product-management/issues/630
New versions of kustomize deprecate the kustomize version option `--short`. The output of that command is also changed. To allow both version to be handled correctly by `furyctl` we now relax the regular expression used to get the tool version to match both outputs.
Nothing.
Nothing.

feat: add support to kustomize version 5.6.0

---

configs/upgrades/ekscluster/1.31.0-1.31.1/pre-distribution.sh.tpl

Remove snapshot controller before upgrade
Relates:
https://github.com/sighupio/distribution/pull/367
Remove snapshot-controller before upgrade from kapp so that it will not be deleted once installed via eks addons
None
- Created a cluster with v1.31.0
- executed `kubectl get deployment -n kube-system snapshot-controller -o yaml`(and all the other components) to check that it's present
- executed cluster upgrade to 1.31.1
- executed `kubectl get deployment -n kube-system snapshot-controller -o yaml`(and all the other components) to check that it's present

feat: remove snapshot-controller from kapp before upgrade

---

configs/upgrades/ekscluster/1.29.6-1.29.7/post-distribution.sh.tpl
configs/upgrades/ekscluster/1.29.6-1.30.2/post-distribution.sh.tpl
configs/upgrades/ekscluster/1.30.1-1.30.2/post-distribution.sh.tpl
configs/upgrades/ekscluster/1.30.1-1.31.1/post-distribution.sh.tpl
configs/upgrades/kfddistribution/1.29.6-1.29.7/post-distribution.sh.tpl
configs/upgrades/kfddistribution/1.29.6-1.30.2/post-distribution.sh.tpl
configs/upgrades/kfddistribution/1.30.1-1.30.2/post-distribution.sh.tpl
configs/upgrades/kfddistribution/1.30.1-1.31.1/post-distribution.sh.tpl
configs/upgrades/onpremises/1.29.6-1.29.7/post-distribution.sh.tpl
configs/upgrades/onpremises/1.29.6-1.30.2/post-distribution.sh.tpl
configs/upgrades/onpremises/1.30.1-1.30.2/post-distribution.sh.tpl
configs/upgrades/onpremises/1.30.1-1.31.1/post-distribution.sh.tpl

Delete resources that are not needed anymore after upgading to logging v5, that updates and deprecates some Loki components.
Relates: https://github.com/sighupio/module-logging/pull/185
In logging v5 some components of Loki have changed kind or name. We need to do some clean up after the upgrade when we are coming from versions that were not using `kapp`.
In versions that were previously using `kapp` this was not needed.
None
None

fix(upgrade-paths): delete old loki resources

---

README.md
cmd/apply.go
cmd/create.go
cmd/download/dependencies.go
internal/apis/kfd/v1alpha2/ekscluster/create/distribution.go
internal/apis/kfd/v1alpha2/ekscluster/create/kubernetes.go
internal/apis/kfd/v1alpha2/ekscluster/creator.go
internal/apis/kfd/v1alpha2/ekscluster/delete/kubernetes.go
internal/apis/kfd/v1alpha2/kfddistribution/create/distribution.go
internal/apis/kfd/v1alpha2/onpremises/create/distribution.go
internal/apis/kfd/v1alpha2/onpremises/create/kubernetes.go
internal/apis/kfd/v1alpha2/onpremises/delete/kubernetes.go

- Simplify readme, dropping information that we already have in the docs, so we don't have to maintain both versions.
- Fix some missing rebranding in README
- Fix some missing rebranding in the logs printed by furyctl
- Improve some of the logs that were leaking implementation details
Relates: #580 
See above
None
None

chore: more rebranding

---

cmd/diff.go
internal/apis/kfd/v1alpha2/ekscluster/create/preflight.go
internal/apis/kfd/v1alpha2/kfddistribution/create/preflight.go
internal/apis/kfd/v1alpha2/onpremises/create/preflight.go

Lower message severity to WARN when diff checker fails but force flag is set.
Fix error message formatting
Fixes #588
Before:
After:
Note: I changed `Skipping` for `Continuing` afterwards taking the screenshot.
None
None

fix: diff checker error when force flag is set

---

cmd/get.go
cmd/get/supported-versions.go
cmd/get/supported-versions_test.go

Change reamining references to KFD to the new branding in the get supported-versions command.
See summary
None
None

chore: change remaining references to KFD

---

internal/legacy/download.go
internal/legacy/furyfile.go
internal/legacy/package_url.go

add new kind in furyfile.yaml so that we can specify external dependencies to download with `furyctl legacy vendor`
Closes:
N/A
Relates:
https://github.com/sighupio/installer-eks/pull/84
add new kind in furyfile.yaml so that we can specify external dependencies to download with `furyctl legacy vendor`
in the `furyfile.yaml` specify external repos like this:
```yaml
versions:
...
bases:
...
external:
- name: terraform-aws-eks
url: git@github.com:terraform-aws-modules/terraform-aws-eks.git
version: v17.24.0
```
none
with this `furyfile.yaml`
```yaml
external:
- name: terraform-aws-eks
url: git@github.com:terraform-aws-modules/terraform-aws-eks.git
version: v17.24.0
```
ran `furyctl legacy vendor`
output:
```
go run main.go legacy vendor --furyfile …
```

feat: add external kind in furyfile for furyctl legacy vendor

---

cmd/apply.go
cmd/delete/cluster.go

Print also the path to the lock file in the messages shown to the user.
So, if your furyctl execution is blocked by the lock file by mistake (a dead process that did not clean up the lock, for example) the user knows which file to delete.
See summary.
Example output:
```
❯ furyctl apply
INFO Downloading distribution...
INFO Compatibility patches applied for v1.31.1
ERRO error while verifying lock file /var/folders/lb/zscvwt_s6fx6qdrfv4g51dsc0000gn/T/furyctl-multipass: lock file exists. This usually means that there is another instance of furyctl running
```
None
It would be nice if the lock file had the PID inside.

feat: print lock file path

---

cmd/dump/template.go
internal/distribution/iac.go
test/e2e/furyctl_test.go

Use the workdir instead of the outputDir for target forlder where to dump the rendered template.
Fixes: #434 
Previously the `dump template` command was using _sometimes_ the `outputDir` as the target where to dump the `distribution` folder containing the rendered templates.
With this change, the `dump template` command will create the `distribution` folder in the working directory and dump the rendered templates there always.
Note that the workdir can be set using the `--workdir` flag, like in the other commands.
If you relied on the command dumping to the output dir you may need to adjust the flags you are using.
I think that naming the outdir outdir is confusing, the outdir is a "datadir" and not an output dir. This directory is used only for internal files.

fix(dump template): use workdir instead of outputDir

---

cmd/dump/cli-reference.go
internal/lockfile/lockfile.go

Use the const that we already had on the iox package for setting file permissions instead of redefining them.
Thanks @al-pragliola for the tip
Relates: #604
See summary
None
None

chore: use iox const for permissions

---

internal/apis/kfd/v1alpha2/ekscluster/create/preflight.go
internal/apis/kfd/v1alpha2/kfddistribution/create/preflight.go
internal/apis/kfd/v1alpha2/onpremises/create/preflight.go
pkg/rulesextractor/ekscluster.go
pkg/rulesextractor/ekscluster_test.go
pkg/rulesextractor/extractor.go
pkg/rulesextractor/extractor_test.go
pkg/rulesextractor/kfddistribution.go
pkg/rulesextractor/kfddistribution_test.go
pkg/rulesextractor/onpremises.go
pkg/rulesextractor/onpremises_test.go

This PR enhances the rules extractor functionality by adding a new `FromNode` feature that allows for more context-aware immutability checks. 
This improvement enables the system to determine if a field should be considered immutable based on the state of other fields in the configuration.
The implementation has been refactored to work both with and without reducers.
Closes: [#398](https://github.com/sighupio/distribution/issues/398)
The PR introduces some modifications to the rules extractor system:
1. Added a new `FromNode` struct that allows for referencing other nodes in the configuration when determining if a rule is safe to modify. for example:
```yaml
- path: .spec.distribution.modules.logging.loki.tsdbStartDate
immutable: true
description: "changes to Loki's TSDB start date have …
```

fix(398): add new from node immutable reducer

---

internal/apis/kfd/v1alpha2/kfddistribution/create/distribution.go
internal/apis/kfd/v1alpha2/onpremises/create/distribution.go

Check for the presence of a default storage class and not only that there are storage classes defined.
Closes: https://github.com/sighupio/distribution/issues/416
Having storage classes defined is not enough, we assume there is at least one default storage class. This PR adds the check for a default SC.
We could drop the check for the presence of a storage class, being that checking for a default one covers also the presence of storage classes, but I left them because we can give better feedback to the user this way.
None
tested for the on-prem and kfddistribution providers.
We could use the structured output (json, yaml) of the command we parse the output from, but I think it's not worth the effort.

fix(onpremises,kfddistribution): check for a default SC

---

.goreleaser.yml

Currently goreleaser sorts tags in the same commit alphabetically. 
This behaviour breaks in case we have multiple tags for the same commits for normal releases(eg. with v0.32.4-rc.0 and v0.32.4 it picks v0.32.4-rc.0 instead of v0.32.4)
We configured goreleaser to sort the tags by creation date
see summary
None

fix: goreleaser sort tags by creator date if there are more than one tag in the same commit
